FROM alpine:3.7 AS busybox-build
LABEL maintainer="Markus Sonderegger <marraison@gmail.com>"

RUN apk add --no-cache \
		bzip2 \
		coreutils \
		curl \
		gcc \
		gnupg \
		linux-headers \
		make \
		musl-dev \
		tzdata \
		ncurses-dev

ARG BUSYBOX_VERSION 

COPY keys.asc /

RUN gpg -q --import keys.asc \
	&&tarball="busybox-${BUSYBOX_VERSION}.tar.bz2" \
	&& curl -fL -o busybox.tar.bz2 "https://busybox.net/downloads/$tarball" \
	&& curl -fL -o busybox.tar.bz2.sign "https://busybox.net/downloads/$tarball.sign" \
	&& gpg --batch --decrypt --output busybox.tar.bz2.txt busybox.tar.bz2.sign \
	&& awk '$1 == "SHA1:" && $2 ~ /^[0-9a-f]+$/ && $3 == "'"$tarball"'" \
		{ print $2, "*busybox.tar.bz2" }' busybox.tar.bz2.txt > busybox.tar.bz2.sha1 \
	&& test -s busybox.tar.bz2.sha1 \
	&& sha1sum -c busybox.tar.bz2.sha1 \
	&& mkdir -p /busybox \
	&& tar -xf busybox.tar.bz2 -C /busybox --strip-components 1 \
	&& rm busybox.tar.bz2*

ADD config /busybox/.config
WORKDIR /busybox

